Repository F1R3BLAZ3/AirBnB_clone_v3, pull requests merged in 2023-10, with the labels that each got.

#14 Task 3 - Added base files and folders for api
  .gitignore
  api/__init_.py
  api/v1/__init_.py
  api/v1/app.py
  api/v1/views/__init_.py
  api/v1/views/index.py
Labels: enhancement

#15 Task 2 - Improve storage
  models/engine/db_storage.py
  models/engine/file_storage.py
Labels: enhancement

#17 Task 4 - Updated index.py, and __init__ filenames
  api/v1/views/index.py
Labels: enhancement

#18 Task 5 - Updated app.py to include custom 404
  api/v1/app.py
Labels: enhancement

#19 Task 7
  api/v1/views/__init__.py
  api/v1/views/cities.py
Labels: enhancement

#20 Task 8
  api/v1/views/__init__.py
  api/v1/views/amenities.py
Labels: enhancement

#21 Task 7
  api/v1/views/cities.py
Labels: bug

#22 Task 9
  api/v1/views/__init__.py
  api/v1/views/users.py
Labels: enhancement

#23 Task 0
  README.md
Labels: documentation

#24 Task 6 - State
  .gitignore
  __pycache__/console.cpython-38.pyc
  api/v1/views/__init__.py
  api/v1/views/states.py
Labels: enhancement

#25 Task 7
  api/v1/views/cities.py
Labels: bug

#28 Task 1
  tests/test_api/test_v1/test_app.py
Labels: enhancement

#29 12 11 reviews
  api/v1/app.py
  api/v1/views/__init__.py
  api/v1/views/places_reviews.py
Labels: enhancement
